/*
 * MethodInfo.java    4:01 AM, August 5, 2007
 *
 * Copyright  2007, FreeInternals.org. All rights reserved.
 * Use is subject to license terms.
 */
package org.freeinternals.format.classfile;

import org.freeinternals.format.classfile.constant.CPInfo;
import org.freeinternals.format.classfile.attribute.AttributeInfo;
import java.io.IOException;
import org.freeinternals.commonlib.core.FileComponent;
import org.freeinternals.commonlib.core.PosDataInputStream;
import org.freeinternals.commonlib.core.FileFormatException;

/**
 * {@code Method} of a class or interface. The {@code Method} structure has the
 * following format:
 *
 * <pre>
 *    method_info {
 *        u2 access_flags;
 *        u2 name_index;
 *        u2 descriptor_index;
 *        u2 attributes_count;
 *        attribute_info attributes[attributes_count];
 *    }
 * </pre>
 *
 * @author Amos Shi
 * @see
 * <a href="https://docs.oracle.com/javase/specs/jvms/se12/html/jvms-4.html#jvms-4.6">
 * VM Spec: Methods
 * </a>
 *
 * <pre>
 * java:S116 - Field names should comply with a naming convention --- We respect the name from JVM Spec instead
 * </pre>
 */
@SuppressWarnings("java:S116")
public class MethodInfo extends FileComponent {

    public final u2 access_flags;
    public final u2 name_index;
    public final u2 descriptor_index;
    public final u2 attributes_count;
    public final AttributeInfo[] attributes;
    private String declaration;
    private String descriptor;
    private String name;

    MethodInfo(final PosDataInputStream posDataInputStream, final CPInfo[] cp) throws IOException, FileFormatException {
        this.startPos = posDataInputStream.getPos();
        this.length = -1;

        this.access_flags = new u2(posDataInputStream);
        this.name_index = new u2(posDataInputStream);
        this.descriptor_index = new u2(posDataInputStream);

        this.attributes_count = new u2(posDataInputStream);
        final int attrCount = this.attributes_count.value;
        if (attrCount > 0) {
            this.attributes = new AttributeInfo[attrCount];
            for (int i = 0; i < attrCount; i++) {
                this.attributes[i] = AttributeInfo.parse(posDataInputStream, cp);
            }
        } else {
            this.attributes = null;
        }

        this.calculateLength();
        this.parse(cp);
    }

    private void calculateLength() {
        this.length = 8;

        for (int i = 0; i < this.attributes_count.value; i++) {
            this.length += this.attributes[i].getLength();
        }
    }

    /**
     * Get the value of {@code attributes}[{@code index}].
     *
     * @param index Index of the method attribute(s)
     * @return The value of {@code attributes}[{@code index}]
     */
    public AttributeInfo getAttribute(final int index) {
        AttributeInfo info = null;
        if (this.attributes != null) {
            info = this.attributes[index];
        }
        return info;
    }

    /**
     * Get the declaration of the field. The declaration is generated by
     * {@code access_flags}, {@code name_index} and {@code descriptor_index}.
     *
     * @return {@code Method} declaration
     */
    public String getDeclaration() {
        return this.declaration;
    }

    /**
     * Get method descriptor.
     *
     * @return Method descriptor
     * @see #name_index
     */
    public String getDescriptor() {
        return this.descriptor;
    }

    /**
     * Generate the modifier of a {@code Method} from the {@code access_flags}
     * value.
     *
     * @return A string for modifier
     */
    public String getModifiers() {
        return AccessFlag.getMethodModifier(this.access_flags.value);
    }

    /**
     * Get method name.
     *
     * @return Method name
     * @see #name_index
     */
    public String getName() {
        return this.name;
    }

    /**
     * Set the declaration string.
     */
    private void parse(final CPInfo[] cpInfo) throws FileFormatException {
        this.descriptor = ClassFile.getConstantUtf8Value(this.descriptor_index.value, cpInfo);
        this.name = ClassFile.getConstantUtf8Value(this.name_index.value, cpInfo);

        //
        String returnType;
        String parameters;

        try {
            returnType = SignatureConvertor.methodReturnTypeExtractor(this.descriptor).toString();
        } catch (FileFormatException se) {
            returnType = String.format("[Unexpected method return type: %s]", this.descriptor);
        }
        try {
            parameters = SignatureConvertor.methodParameters2Readable(this.descriptor);
        } catch (FileFormatException se) {
            parameters = String.format("[Unexpected method parameters: %s]", this.descriptor);
        }

        this.declaration = String.format("%s %s %s %s",
                this.getModifiers(), returnType, this.name, parameters);
    }
}
